Looks like kees slipped in a patch without updating git.  Merge it in.

diff --git a/local/xvfb-run b/local/xvfb-run
--- a/local/xvfb-run
+++ b/local/xvfb-run
@@ -149,45 +149,31 @@ trap clean_up EXIT
 # directory to house one.
 if [ -z "$AUTHFILE" ]; then
     XVFB_RUN_TMPDIR="$(mktemp -d -t $PROGNAME.XXXXXX)"
-    AUTHFILE="$XVFB_RUN_TMPDIR/Xauthority"
+    AUTHFILE=$(tempfile -n "$XVFB_RUN_TMPDIR/Xauthority")
 fi
 
 # Start Xvfb.
-tries=1000
-while test $tries -gt 0; do
-    tries=$((tries-1))
-    MCOOKIE=$(mcookie)
+MCOOKIE=$(mcookie)
+tries=10
+while [ $tries -gt 0 ]; do
+    tries=$(( $tries - 1 ))
     XAUTHORITY=$AUTHFILE xauth source - << EOF >>"$ERRORFILE" 2>&1
 add :$SERVERNUM $XAUTHPROTO $MCOOKIE
 EOF
     XAUTHORITY=$AUTHFILE Xvfb ":$SERVERNUM" $XVFBARGS $LISTENTCP >>"$ERRORFILE" 2>&1 &
     XVFBPID=$!
 
-    # Test PID of Xvfb and contents of the X server lock file
-    # (use numerical comparison to avoid whitespace issues).
-    # If the display was in use the Xvfb process will die on its own.
-    LOCKPID=`cat /tmp/.X${SERVERNUM}-lock)` 2>/dev/null
-    if [ -z $LOCKPID ]; then
+    sleep "$STARTWAIT"
+    if kill -0 $XVFBPID 2>/dev/null; then
         break
-    fi
-    if [ "$XVFBPID" -eq $LOCKPID ]; then
-        break
-    fi
-    # The display is in use so try another one (if '-a' was specified).
-    if [ "$AUTONUM" ]; then
+    elif [ -n "$AUTONUM" ]; then
+        # The display is in use so try another one (if '-a' was specified).
         SERVERNUM=$(find_free_servernum)
         continue
     fi
-    error "display :$SERVERNUM already in use"
+    error "Xvfb failed to start" >&2
     exit 1
-
 done
-
-sleep "$STARTWAIT"
-if ! kill -0 $XVFBPID 2>/dev/null; then
-  echo "Xvfb failed to start" >&2
-  exit 1
-fi
 
 # Start the command and save its exit status.
 set +e
